### ISSUE TITLE
Can't delete phone number on some countries

### ISSUE THREAD

**Issue by thanhthan** [webcat12345/ngx-intl-tel-input#250] opened 2020-02-26 09:48 UTC
Hi Team,
I have the issue on deleted on textbox with some countries. I selected  American Samoa/ Dominica/ Barbados then enter number phone to textbox and used Backspace to delete number but i can't delete it. Can you please help me to take a look on that.
Thanks.

**Comment by pasevin** [comment] 2020-03-11 16:43
I will have to look into it. But not sure when I have time...

**Comment by pasevin** [comment] 2020-03-11 21:23
Dupe of: https://github.com/webcat12345/ngx-intl-tel-input/issues/217

**Comment by pasevin** [comment] 2020-03-15 11:58
Should be fixed in new version v2.3.4

**Closed by pasevin** 2020-03-15 11:58 UTC
Labels: bug, duplicate
