### ISSUE TITLE
Getting 'ngx-intl-tel-input' to work with "@ng-bootstrap/ng-bootstrap"

### ISSUE THREAD

**Issue by HockeyJustin** [webcat12345/ngx-intl-tel-input#372] opened 2021-03-24 10:43 UTC
Hi,

This library looks great. 

I am using "@ng-bootstrap/ng-bootstrap" rather than "ngx-bootstrap". I believe they are very similar libraries.

I tried installing this into my angular project without "ngx-bootstrap" to avoid confusion/ library clashes, but i get 

> An error occurred during the build:
> Error: The target entry-point "ngx-intl-tel-input" has missing dependencies:
>  - ngx-bootstrap/utils
>  - ngx-bootstrap/dropdown

Is there an easy way to get this to work with "@ng-bootstrap/ng-bootstrap" please?

NOTE: while ngx-bootrstrap was once dominant, "@ng-bootstrap/ng-bootstrap" now outpaces it for weekly downloads
ngx-bootrstrap: 243,398
@ng-bootstrap/ng-bootstrap: 399,438

**Comment by pasevin** [comment] 2021-03-26 11:31
Duplicate of https://github.com/webcat12345/ngx-intl-tel-input/issues/304

**Closed by pasevin** 2021-03-26 11:31 UTC
